export const programmers = [
  {
    id: "e4ba2bc2b45bf4a5dfa2febef211431a",
    firstName: "Karen",
    lastName: "Darbinyan",
    phone: "notDefined",
    email: "kar31100@gmail.com",
    education: "YSU",
    workExperience: "alam asxarh",
    trainings: "RELQ",
    imagePath: "./img/KarenDarbinyan.jpg",
  },
  {
    id: "fd4be4f20b07a634edda284a59c1667e",
    firstName: "Alexandr",
    lastName: "Hamabrdzumyan",
    phone: "notDefined",
    email: "kar31100@gmail.com",
    education: "YSU",
    workExperience: "alam asxarh",
    trainings: "RELQ",
    imagePath: "./img/AlexandrHamabrdzumyan.jpg",
  },
  {
    id: "9fd3933c5597b550b337cbe9e2e9c3b1",
    firstName: "Hasmik",
    lastName: "Gevorgyan",
    phone: "notDefined",
    email: "kar31100@gmail.com",
    education: "YSU",
    workExperience: "alam asxarh",
    trainings: "RELQ",
    imagePath: "./img/HasmikGevorgyan.jpg",
  },
  {
    id: "f07be7451e702a68a9f738c1cf253f94",
    firstName: "Lusine",
    lastName: "Yeremyan",
    phone: "notDefined",
    email: "kar31100@gmail.com",
    education: "YSU",
    workExperience: "alam asxarh",
    trainings: "RELQ",
    imagePath: "./img/LusineYeremyan.jpg",
  },
  {
    id: "bdc1b39c16d4de76e35963d687065e4c",
    firstName: "Anahit",
    lastName: "Khechumyan",
    phone: "notDefined",
    email: "kar31100@gmail.com",
    education: "YSU",
    workExperience: "alam asxarh",
    trainings: "RELQ",
    imagePath: "./img/AnahitKhechumyan.jpg",
  },
  {
    id: "ff5db42b1681fcc5cf86cf51ddfa76d8",
    firstName: "Ani",
    lastName: "Antonyan",
    phone: "notDefined",
    email: "notDefined",
    education: "notDefined",
    workExperience: "notDefined",
    trainings: "RELQ",
    imagePath: "./img/AniAntonyan.jpg",
  },
  {
    id: "90cd6645a9ebc295d947cc49bd5ca8f4",
    firstName: "Anna",
    lastName: "Hayriyan",
    phone: "notDefined",
    email: "annhayriyan@gmail.com",
    education: "ASUE",
    workExperience: "Scott logistics",
    trainings: "RELQ",
    imagePath: "./img/AnnaHayriyan.jpg",
  },
  {
    id: "ae6647034d9122b5cc617bd172e45a08",
    firstName: "Armenak",
    lastName: "Qocharyan",
    phone: "notDefined",
    email: "qocharyanarmenak@gmail.com",
    education: "Բարձրագույն զինվորական",
    workExperience: "ՀՀ ՊՆ",
    trainings: "Relq School",
    imagePath: "./img/ArmenakQocharyan.jpg",
  },
  {
    id: "92ed2713f05fd8a6b599fd1f3841d488",
    firstName: "Arusyak",
    lastName: "Aghajanyan",
    phone: "notDefined",
    email: "aghajanyanarusyak@gmail.com",
    education: "YSUGU",
    workExperience: "InecoBank CJSC, Risk meneger",
    trainings:
      "BasicItCenter,UNDP Armenia Accelerator5,HTI Armenia C++ basic, SmartCode,Relq Technology",
    imagePath: "./img/ArusyakAghajanyan.jpg",
  },
  {
    id: "f60466711386c60be91ec8d98b0f2821",
    firstName: "Afina",
    lastName: "Panyan",
    phone: "notDefined",
    email: "notDefined",
    education: "notDefined",
    workExperience: "notDefined",
    trainings: "Relq",
    imagePath: "./img/AfinaPanyan.jpg",
  },
  {
    id: "e755adffa8d30bffbc70f54535f6ac30",
    firstName: "Babken",
    lastName: "Tadevosyan",
    phone: "notDefined",
    email: "notDefined",
    education: "notDefined",
    workExperience: "notDefined",
    trainings: "Relq",
    imagePath: "./img/BabkenTadevosyan.jpg",
  },
  {
    id: "cfe5176211b1a6308bb6fed2c114a49a",
    firstName: "Hasmik",
    lastName: "Gevorgyan",
    phone: "notDefined",
    email: "notDefined",
    education: "notDefined",
    workExperience: "notDefined",
    trainings: "Relq",
    imagePath: "./img/HasmikGevorgyan.jpg",
  },
  {
    id: "a45fdb1a0c63fb9dddd689fe9dd6e12d",
    firstName: "Hermine",
    lastName: "Melkumyan",
    phone: "notDefined",
    email: "notDefined",
    education: "notDefined",
    workExperience: "notDefined",
    trainings: "Relq",
    imagePath: "./img/HermineMelkumyan.jpg",
  },
  {
    id: "890027f7e41d7f058127fe5845ce81ff",
    firstName: "Hermine",
    lastName: "Sahakyan",
    phone: "notDefined",
    email: "notDefined",
    education: "notDefined",
    workExperience: "notDefined",
    trainings: "Relq",
    imagePath: "./img/HermineSahakyan.jpg",
  },
  {
    id: "dc1c4b0e0585e191cdc7e09f51661ee6",
    firstName: "Larine",
    lastName: "Danielyan",
    phone: "notDefined",
    email: "danielyanlari@gmail.com",
    education: "Economics and Menegment",
    workExperience: "Martuninsky district Medical Association",
    trainings: "Relq",
    imagePath: "./img/LarineDanielyan.jpg",
  },
  {
    id: "8badda945821be42a425a4a0b6e5e79f",
    firstName: "Liana",
    lastName: "Dashyan",
    phone: "notDefined",
    email: "dashyanlian@gmail.com",
    education: "YSU",
    workExperience: "GYU NGO",
    trainings: "Relq",
    imagePath: "./img/LianaDashyan.jpg",
  },
  {
    id: "e1accb06e02a444f96af3d9bb43160e2",
    firstName: "Lusine",
    lastName: "Yeremyan",
    phone: "notDefined",
    email: "lusineer@gmail.com",
    education: "Economist",
    workExperience: "Municipality",
    trainings: "Relq, MIC",
    imagePath: "./img/LusineYeremyan.jpg",
  },
  {
    id: "d443e2e6eb3f9a3de8a7ad61af60b9fa",
    firstName: "Lusine",
    lastName: "Petrosyan",
    phone: "notDefined",
    email: "plusine99@gmail.com",
    education: "Armenian State University faculty of Radiophysics",
    workExperience: "notDefined",
    trainings: "Relq",
    imagePath: "./img/LusinePetrosyan.jpg",
  },
  {
    id: "c51571cc693972cd8cc41d8fef652cf6",
    firstName: "Karen",
    lastName: "Darbinyan",
    phone: "notDefined",
    email: "kar31100@gmail.com",
    education: "YSU",
    workExperience: "alam asxarh",
    trainings: "RELQ",
    imagePath: "./img/KarenDarbinyan.jpg",
  },
  {
    id: "d4abcecc0d58675cfa5fe5c2dd51d1ee",
    firstName: "Marat",
    lastName: "Harutyunyan",
    phone: "notDefined",
    email: "maratharutyunyan.mh.mh@gmail.com",
    education: "ASIPCS",
    workExperience: "EL Market",
    trainings: "Relq School",
    imagePath: "./img/MaratHarutyunyan.jpg",
  },
  {
    id: "da1e94b060048e4787e1f8af6a3f3fd5",
    firstName: "Narek",
    lastName: "Tovmasyan",
    phone: "notDefined",
    email: "Narektom333@gmail.com",
    education: "ASUE",
    workExperience: "Ameria Bank",
    trainings: "Relq School",
    imagePath: "./img/NarekTovmasyan.jpg",
  },
  {
    id: "f8ff2340cb4a144285e1f09d8f98e91f",
    firstName: "Seda",
    lastName: "Shahnazaryan",
    phone: "notDefined",
    email: "shahnazaryan.seda@mail.ru",
    education: "Higher Education:Historian",
    workExperience: "notDefined",
    trainings: "TechBoost4Women,RELQ technology school",
    imagePath: "./img/SedaShahnazaryan.jpg",
  },
  {
    id: "a1250182318d3e3bf59696894c028fbd",
    firstName: "Seryozha",
    lastName: "Asatryan",
    phone: "notDefined",
    email: "seryozha.asatryan02@gmail.com",
    education: "Economics",
    workExperience: "notDefined",
    trainings: "Relq School",
    imagePath: "./img/SeryozhaAsatryan.jpg",
  },
  {
    id: "dc273c35a887b3c19abcfdcf3caa11f7",
    firstName: "Sevak",
    lastName: "Stepanyan",
    phone: "notDefined",
    email: "stepanyansevak9@gamil.com",
    education: "Economics and Menegment",
    workExperience: "notDefined",
    trainings: "Relq School",
    imagePath: "./img/SevakStepanyan.jpg",
  },
  {
    id: "9fb54f5529f054c9f91929e100ea5964",
    firstName: "Silva",
    lastName: "Ohanyan",
    phone: "notDefined",
    email: "notDefined",
    education: "notDefined",
    workExperience: "notDefined",
    trainings: "Relq School",
    imagePath: "./img/SilvaOhanyan.jpg",
  },
  {
    id: "aca784644bf07dcb8009d65c24618625",
    firstName: "Suren",
    lastName: "Galstyan",
    phone: "notDefined",
    email: "notDefined",
    education: "notDefined",
    workExperience: "notDefined",
    trainings: "Relq School",
    imagePath: "./img/SurenGalstyan.jpg",
  },
  {
    id: "fe0edf397ca5e14cd7d3f2367fe539b0",
    firstName: "Tigran",
    lastName: "Martirosyan",
    phone: "notDefined",
    email: "martirosyant01@mail.ru",
    education: "notDefined",
    workExperience: "notDefined",
    trainings: "Relq School",
    imagePath: "../img/person-icon.jpg",
  },
];
